### ISSUE TITLE
Failed to sync https://github.com/aboutcode-org/vulnerablecode-data

### ISSUE THREAD

**Issue by keshav-space** [aboutcode-org/federatedcode#40]
sync request for https://github.com/aboutcode-org/vulnerablecode-data fails with.

```python
IntegrityError('null value in column "purl" of relation "fedcode_package" violates not-null constraint\nDETAIL:  Failing row contains (, , t, 0965fded-2eab-4517-a0d0-3da936505942, null, null, 1).') 
 Traceback (most recent call last):
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/query.py", line 946, in get_or_create
    return self.get(**kwargs), False
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
fedcode.models.Package.DoesNotExist: Package matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "../federatedcode/venv/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "purl" of relation "fedcode_package" violates not-null constraint
DETAIL:  Failing row contains (, , t, 0965fded-2eab-4517-a0d0-3da936505942, null, null, 1).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../federatedcode/fedcode/management/commands/tasks.py", line 29, in sync_task
    importer.run()
  File "../federatedcode/fedcode/importer.py", line 79, in run
    pkg_handler(
  File "../federatedcode/fedcode/importer.py", line 120, in pkg_handler
    pkg, _ = Package.objects.get_or_create(purl=package, service=default_service)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/query.py", line 953, in get_or_create
    return self.create(**params), True
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "../federatedcode/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "../federatedcode/venv/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "purl" of relation "fedcode_package" violates not-null constraint
DETAIL:  Failing row contains (, , t, 0965fded-2eab-4517-a0d0-3da936505942, null, null, 1).
```

**Comment by keshav-space** [comment]
This is now fixed in https://github.com/aboutcode-org/vulnerablecode-data/pull/2
